### ISSUE TITLE
How to return purchased items from a Shopify store?

### ISSUE THREAD

**Issue by heytulsiprasad** [thetrevorharmon/sell-things-fast#10]
Hey @thetrevorharmon, I'm a huge fan of Shopify and how easy it makes for us to build the actual site itself instead of worrying about many things.

However, I'm concerned about what if the user wants to:
- see the list of purchased items from the store?
- return any previously purchased item?
- track current orders?

I am very new to Shopify so it's been bugging me lately, thought to ask it here. Thanks for this project 👍

**Comment by thetrevorharmon** [comment]
Hi @heytulsiprasad,

Many of those things are done via an 'admin' portal for existing customers. That falls outside of the scope of what this repo covers (and what I really know about). I would try [a Google search like this](https://www.google.com/search?q=liquid+template+shopify+user+portal&oq=liquid+template+shopify+user+portal&aqs=chrome..69i57j33i22i29i30.4760j0j7&sourceid=chrome&ie=UTF-8) or maybe [this Shopify help page](https://shopify.github.io/liquid-code-examples/example/customer-login).

Good luck.
