### ISSUE TITLE
Something is triggering GraphQL queries

### ISSUE THREAD

**Issue by lukebennett88** [thetrevorharmon/sell-things-fast#2]
If you go to https://sell-things-fast.netlify.com and look at the network tab, you'll see a ton of GraphQL requests.

It looks like this is caused by the useEffect dependancy array on line 70 of the `StoreContext.js` file.

Removing `store` and `setStore` from the array seems to fix the problem (no more infinite loop).

Unfortunately this causes the `react-hooks/exhaustive-deps` ESLint rule to be triggered. Not sure if there is an elegant solution to get around this or not.

**Comment by nandorojo** [comment]
It seems like the client variable is a static variable of the entire app. If you replace store.client with client directly, then you can avoid including the store in the dependencies array.

Also, the linter does not require you to add setStore to the array, since this function will never change.

**Comment by lukebennett88** [comment]
@nandorojo so like this, with nothing in the dependancy array?

```jsx
useEffect(() => {
  const initializeCheckout = async () => {
    // Check for an existing cart.
    const isBrowser = typeof window !== 'undefined';
    const existingCheckoutId = isBrowser
      ? localStorage.getItem(SHOPIFY_CHECKOUT_STORAGE_KEY)
      : null;

    if (existingCheckoutId) {
      try {
        const checkout = await fetchCheckout(client, existingCheckoutId);
        // Make sure this cart hasn’t already been purchased.
        if (!checkout.completedAt) {
          setCheckoutInState(checkout, setStore);
          return;
        }
      } catch (e) {
        localStorage.setItem(SHOPIFY_CHECKOUT_STORAGE_KEY, null);
      }
    }

    const newCheckout = await createNewCheckout(client);
    setCheckoutInState(newCheckout, setStore);
  };

  initializeCheckout();
}, []);
```

Seems to work and my linter is no longer yelling at me 😂.
